- background.js
Currently the regular expression matches all hostnames that end with hostnames defined in `FACEBOOK_DOMAINS`, which also includes hostnames like [deletefacebook.com](https://deletefacebook.com/). This PR makes sure that only subdomains are matched instead.
Fixes #49
> Make sure that only configured domains and their subdomains are contained

- src/manifest.json
We will need storage permission in a future release, and we only want to
interrupt the use with the prompt once.
> fix #132: add storage permission

- src/background.js
[Onava](https://www.onavo.com) is a VPN service owned by facebook.
> Add "onavo.com" as facebook domain

- src/background.js
- test/features/contain.test.js
This strips `fbclid` so it can't be used to link browsing sessions when tabs are re-opened inside-outside of Facebook Container.
However, I'm considering if we should *always* strip `fbclid` from all urls to cover a scenario where `fbclid` could link the uncontained context to an FB account with a link to a non-FB site.
E.g. an email notification contains a link to `https://www.example.com/?fbclid=12345` which embeds a request to `www.facebook.com`.
In that scenario, the embedded resource request from `example.com` to `facebook.com` includes the un-contained cookies and the `fbclid` value in the `Referer` header, which could effectively re-associate the un-contained cookies to the FB account.
> fix #178: strip fbclid from urls when reopening

- src/background.js
There are still [too many issues](https://github.com/mozilla/contain-facebook/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+whatsapp) to include whatsapp domains.
> for #139: remove whatsapp domains

- src/manifest.json
Makes the icon show up when system (and therefore default Firefox) theme is in light mode ...
> fix #227: change default_icon to the darker icon

- src/background.js
- test/setup.js
Fixes #228 
Removed the `await` from the call to `updateBrowserActionIcon` inside the request handler, because we don't need to wait for it to finish (and it does a `fetch` every time) in order to further process the request. Actually I'm not sure we need the call there at all, because the tabs.onUpdated listener fires in case the url changes anyway.
> Update browserAction for active tab when initializing and window change

- src/panel.js
After the fix introduced in #224 the badge text is no longer removed when the panel is shown, because the badge is now tab specific.
> Remove popup badge when panel is shown

- src/background.js
Simple fix for the popup panel showing wrong information in private browsing (alternative to #232).
> Disable browserAction in Private Browsing

- src/background.js
The `getMACAssignment` and `shouldContainInto` checks are unnecessarily made in two places, let's consolidate them into one.
> Refactoring to remove code duplication

- src/_locales/en/messages.json
- src/background.js
- src/content_script.js
- src/panel.css
- src/panel.js
Adds the "in-fbc" panel which should show when the user is on a site they've already added to the facebook container. This is a different panel than the one that shows when a user is on Facebook, or one of the other sites added by default.
I'm currently getting a "no-trackers" panelId message when visiting a site I've added to the container, so I think we may still need to set up a separate message for when someone is visiting a site they've previously added to the container.
> Add "in-fbc" panel.

- src/_locales/en/messages.json
- src/panel.css
Also fix one more "Facebook" typo
> Use typographical apostrophes in messages

- src/content_script.js
Resolve sites that the FBC add-on break. 
Verified with the following sites:
+ https://www.modo.coop/plans/#tile-trip-calculator (Calculate trip) 
+ https://bazqux.com/ (Login w/ Facebook prompt) 
+ https://telemetry.mozilla.org/update-orphaning/ (Chart should animate/load)
+ https://air.mozilla.org/ (Login restored) 
Untested: 
+ https://sso.mozilla.com/workday (Login with Mozilla LDAP)
> Non fb site breakage

- src/content_script.js
I used the following snippet to solve the onload race condition/overwrite: https://www.systutorials.com/241284/add-my-own-window-onload-safely-without-overwriting-old-ones/ 
Test the following sites. _Note that unless noted, these should all happen without any scrolling/mouse clicks._ 
+ https://stackoverflow.com/users/login (SSO should get badged) 
+ https://telemetry.mozilla.org/update-orphaning (Graph should load, no badges) 
+ https://imgur.com/signin (SSO should get badged) 
+ https://www.buzzfeed.com/anamariaglavan/useful-products-youll-want-to-try-out-asap (Share buttons should get badged) 
Also added badge support for Deezer:
+ https://www.deezer.com/us/login
> Window.onload Overwrite Issue

- src/content_script.js
Used similar solution/issue located here: https://github.com/kanap0nta/QuickDrag-WE/issues/52 
Verify the following sites: 
- https://www.geekzone.co.nz/login.asp (No badge or console errors) 
- https://stackoverflow.com/users/login (Login should badge without click, on page load) 
- https://telemetry.mozilla.org/update-orphaning/ (Graphs should load, no badges) 
- https://www.buzzfeed.com/bekoconnell/cheap-products-everything-50?origin=hpp (Lots of badges) 
- https://imgur.com/signin (Login should badge without click, on page load) 
- https://gab.com
Also added detection support for the following: 
+ https://secure.meetup.com/login/
+ https://secure.meetup.com/register
+ https://www.meetup.com (Click "Sign Up" for Modal) 
+ https://www.meetup.com/Greater-Tulsa-Small-Business-Meetup/events …
> Fixed #384. Revised window.onload overload function

- package.json
- src/content_script.css
- src/content_script.js
- src/manifest.json
Check the following sites: 
To test – You should only see ONE share badge per page. On any other FB share buttons, hover over button to make that badge appear. 
+ https://www.estadao.com.br/
+ https://www.theguardian.com/commentisfree/2019/may/24/next-tory-leader-panel-theresa-may-conservatives#comments
+ https://www.buzzfeed.com/bekoconnell/cheap-products-everything-50
> Remove duplicate share badges

- src/content_script.js
Do not call window.onload function from the load event listener: this causes the onload function to run twice, which breaks some websites.
Fixes #420
Example HTML which shows that the window.onload function is run twice before this patch:
```
<!doctype html>
<html>
<head></head>
<body>
<script>
times = 0;
window.onload = function() {
console.log(++times + ": onload called");
};
</script>
</body>
</html>
```
The console will display the following with 1.9.1:
```
1: onload called
2: onload called
```
> Prevent window.onload from being run twice

- package-lock.json
- src/content_script.css
- src/content_script.js
- src/manifest.json
Test the following sites: 
+ #406 – https://lifehacker.com/what-to-do-if-you-miss-your-flight-1834889383 (Hover over fixed Facebook button at bottom right of page. Tooltip should be visible) 
+ #424 – haaretz.com (Should not have floating badge in navigation) 
+ #425 – https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5 (Should not have floating badge to left of article content)
> Fixed #389, Cleans up badges from no-longer-active elements

- src/background.js
Added "workplace.com" domains to the background.js to open inside the Facebook Container. 
+ Visit  [workplace.com](https://workplace.com)
+ Visit [work.facebook.com](https://work.facebook.com)
Both of these URLs should open inside the Facebook Contianer. 
https://send.firefox.com/download/26f42108e4ebbd14/#q9ptmTfz5G6NpodttmmmXQ
> Add workplace domain to background js

- package-lock.json
- package.json
- src/background.js
- src/manifest.json
Stops the Spotify login loop as show on #447 
1. Go to https://www.spotify.com
2. Click login (https://accounts.spotify.com/en/login) 
3. Click prompt to allow FBC (See screenshot) 
4. Reload page/log into Facebook
5. Go to https://www.spotify.com
6. https://open.spotify.com
**Expected results:**
All three websites (www, auth and open) should be inside the Facebook Container
> Spotify Loop Fix

- src/manifest.json
The extension's functionality should resemble the Multi-Account Containers and be disabled in Incognito mode.
> Disable extension in incognito mode

- src/content_script.js
Calling querySelectorAll() in a loop may traverse the DOM tree multiple times. This can be very slow on complex websites[1]. Based on Gecko profiler, joining the selectors and calling querySelectorAll() only once can be over twice as fast[2]. 
[1]: For example, https://hg.mozilla.org/releases/mozilla-release/file/tip/layout/painting/FrameLayerBuilder.cpp
[2]: before https://perfht.ml/2PgcPYf, after https://perfht.ml/2N5qSNx
> Perf: Join the selectors and call querySelectorAll() only once

- .gitignore
- .travis.yml
- package-lock.json
- package.json
- test/functional/.eslintrc.js
- test/functional/badging.test.js
- test/functional/fixtures/badges.html
- test/functional/setup.js
Copies the `src` and [`test/functional/fixtures/badge.html`](https://github.com/mozilla/contain-facebook/blob/cb25cf8ee24c9a4b27362768ddf354763e4c718d/test/functional/fixtures/badges.html) into `build`, loads FBC using geckodriver, opens the `badge.html` and [checks](https://github.com/mozilla/contain-facebook/blob/cb25cf8ee24c9a4b27362768ddf354763e4c718d/test/functional/badging.test.js) if an element with `fbc-badge` was added.
Locally executable by either `npm run test-functional`, which closes Firefox after completion, or `npm run test-functional-dev` to keep Firefox open after the tests exit.
Also added to the travis build.
API Docs for selenium webdriver/geckodriver: https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Driver.html
> Add functional test for badging

- src/_locales/en/messages.json
There was a missing interstitial panel during the "adding site" process of the new site management feature. These strings account for it. See additional info in [the issue](https://github.com/mozilla/contain-facebook/issues/586).
> Fixed #586 - Added missing strings

- src/background.js
- src/panel.css
- src/panel.js
- Navigate to any about: page (ex: `about:about`)
- Open panel, try to click on "Allow Site in Facebook Container"
- **Expected**: Button is grayed out, clicking does nothing
> Fixed #588 - Added logic to stop about: pages from being added to the container

- src/panel.css
- src/panel.js
Fixes #585 
Added interstitial confirmation panel when adding site to the container.
Revised flow to include confirmation panel when removing site, if triggered from the main panel (and not the site list manager panel)
Reference: 
- [InVision Spec](https://mozilla.invisionapp.com/share/WNREP95GJ4V#/387099855_Sites_Allowed_Into_FBC)
- Navigate to any non-FB container site in browser (Ex: firefox.com) 
- Open panel, click "Allow Site in Facebook Container"
- Expected: See "Allow" confirmation panel. 
- Navigate to any CUSTOM CONTAINED SITE inside the FB container site
- Open panel, click "Remove Site from Facebook Container" 
- Expected: See "Remove" confirmation panel (Exactly what is shown when going to "Sites Allowed in Facebook Container" > Clicking "X" on _Sites You've Allowed_ list)
> Fixed #585 - Added confirmation interstitial when adding/removing sites from the container 

- src/panel.js
- Fixed #608 
Added interstitial when removing sites from the first page of the doorhanger. Revised flow to include confirmation panel when removing site, if triggered from the main panel (and not the site list manager panel)
Reference: 
- [InVision Spec](https://mozilla.invisionapp.com/share/WNREP95GJ4V#/387099855_Sites_Allowed_Into_FBC)
- Navigate to any CUSTOM CONTAINED SITE inside the FB container site
- Open panel, click "Remove Site from Facebook Container" 
- Expected: See "Remove" confirmation panel (Exactly what is shown when going to "Sites Allowed in Facebook Container" > Clicking "X" on _Sites You've Allowed_ list)
> Fixed #608 - Added removal confirmation 

- package.json
- src/background.js
- src/manifest.json
This PR addresses issues with allow-listed domains requesting/loading resources on Facebook. This happens on https://apps.facebook.com where Facebook has authorized the game developers to load resources from their websites into Facebook.  
- Fixes #663 
- Log into Facebook
- Go to https://apps.facebook.com/wordswithfriends/
- Expected results: It loads without error.
- Specifically, the FB.js SDK (`https://connect.facebook.net/en_US/sdk.js`) should load
> Allow external scripts to be loaded if  frame ancestor is valid Facebook domain

- package.json
- src/background.js
- src/manifest.json
This PR adds https://facebookrecruiting.com/ as a default Facebook domain. 
- Go to https://facebookrecruiting.com/
- Expected: Opens up inside the Facebook container
> Add facebookrecruiting.com domain

- src/background.js
The blog on https://oversightboard.com/ is broken for users with Facebook Container installed. All their CSS and JS is hosted on `fbcdn.net`, which gets blocked by the container.
Since oversightboard.com is run by Facebook, I think the easiest fix for that is to add the domain to the list of Facebook domains, so that any access to that site happens within the Facebook Container, where everything works fine. :)
> Add oversightboard.com to the list of Facebook domains.

- src/background.js
`bulletin.com` is a new Facebook site. Currently does not appear to be usable with Facebook Container on since it tries to GET a large number of resources from `fbcdn.com`.
> Add bulletin.com to the list of Facebook domains

- src/_locales/en/messages.json
- src/background.js
- src/content_script.css
- src/content_script.js
- src/panel.js
- test/.eslintrc.js
- test/functional/.eslintrc.js
@maxxcrawford just an idea right now ... couple things I noticed that I might need help with ...
* The panel pops up when you select any email input field - should we make it only pop up when someone clicks the fence badge?
* The fence badge in the email input field conflicts with the relay badge in the email input field if both are installed. Any way to detect the relay badge and remove the fence in that case?
* Probably more I haven't thought of?
> add panel for email fields to link to relay

- package-lock.json
- package.json
- src/background.js
- src/content_script.js
- src/manifest.json
This PR scopes the email input prompt to only sites that have had Facebook resources blocked on them. 
**Test case: No email prompt expected**
- Navigate to https://bugzilla.mozilla.org
- Click "Login" button
- Focus on "Email" field (if not done automatically) 
- **Expected:** There should be no FBC badge on the input field. 
**Test case: Email prompt visible**
- Navigate to https://www.airbnb.com/login 
- **Expected:** The "Continue with Facebook" button should have a FBC badge
- Click "Continue with Email" button
- **Expected:** The email input field should have a FBC badge
> Fix #783 - Email prompt badging

- package-lock.json
- package.json
- src/content_script.css
- src/content_script.js
This PR solves a few different items: 
- Check for `isTrusted` for any click events
- Check Login Button detection
- Bumps all outdated dependencies (via `npm audit`)
> Only open prompt when user clicks badge

- src/content_script.css
- src/panel.css
This fixes the bug that overrode site CSS present in 2.3.3, which has now been replaced with 2.3.4 (repackaged 2.3.2).
> Remove overriding CSS values from body

- src/content_script.js
> Fix ContentScriptInit target

- src/content_script.css
Addresses #886 which is caused by too general application of styling on the `is-hidden` class
> tighten up CSS selectors on is-hidden class

- package-lock.json
- package.json
- src/background.js
- src/manifest.json
While reviewing https://github.com/mozilla/contain-facebook/issues/699, a user mentioned FB URLs that were missing from the container list. Added! 
To test: 
- Install FBC
- Navigate to:
- https://www.internalfb.com/login
- https://fburl.com/debugjs (will redirect to the above URL)
- https://mapillary.com (#843)
- https://fb.me (#847) 
- Expected: URLs re-open inside the Facebook Container
> Add Meta owned URLS to FBC contained URLs list

- src/panel.js
- test/features/add-domain-to-fbc.test.js
Still not 100% sure why it needs a pause between the two commands:
- `await background.browser.runtime.onMessage.addListener.yield({message: "remove-domain-from-list", ...})`
- `await background.browser.runtime.onMessage.addListener.yield({message: "what-sites-are-added"})`
&hellip; but here we are. Seems to work since I get:
>   34 passing (5s)
>  1 passing (3s)
<details>
<summary><kbd>npm test</kbd></summary>
```sh
npm test
> contain-facebook@2.3.9 test
> eslint src test && npm run coverage && npm run test-functional
> contain-facebook@2.3.9 coverage
> nyc --reporter=html --reporter=text mocha --reporter=progress test/setup.js test/features/*.test.js --timeout 60000
[▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]
34 passing (5s) …
```
> Fix 'runtime message removeDomain > should have removed the domain' test
