- background.js
- manifest.json
Note: this will prompt existing users for a new permission.
> fix #23: use management API to detect MAC

- background.js
Fixes #19, Fixes #56 and active status mentioned in #63
> Maintain tab states: active, index

- background.js
Handle cases where Facebook is assigned or unassigned to "Always open in" using Multi-Account Containers after installation/enabling of contain-facebook or browser-start. To achieve this it was necessary to change the initialization behavior. The request handler is now always set-up and the check for MAC assignment always happens in the request handlers if it's an FACEBOOK_DOMAIN. Cookies are always cleared on initialization, regardless of MAC assignment. A side-effect is that, if just one specific domain is assigned with MAC, all other FACEBOOK_DOMAINS will still get contained from contain-facebook.
Also makes sure (by awaiting) that the Facebook container is correctly detected or created and hence should avoid that [this](https://github.com/stoically/contain-facebook/blob/1cceca2ccafc28b …
> Handle Multi-Account Containers Assignment edge-cases

- background.js
The fix in #44 got lost while resolving conflicts in #54, oops.
> Fix RegExp again

- background.js
> Prevent redirects and MAC-incompatibility from opening two tabs

- background.js
As discussed with @TanviHacks 
Fixes #80
> Remove cookies in all containers except in Facebook Container when initializing

- background.js
Combines https://github.com/mozilla/contain-facebook/pull/42 and https://github.com/mozilla/contain-facebook/pull/46. Thanks @perflyst and @rosslh !
Fixes #45
> Add more facebook domains 45

- background.js
> Maintain windowId

- src/background.js
Counter part commit: https://github.com/mozilla/multi-account-containers/pull/1188
> Send jailed domains

- src/background.js
lookaside.fbsbx.com is used in displaying documents in Facebook groups
> Added lookaside.fbsbx.com domain

- src/background.js
All recent domain additions. Includes
* edge and pixel domains with Akamai, appspot, and others
* additional messenger domain
* additional fbsbx CDN domains
* I've attempted to dedupe the domains, [very much like the outcome of this discussion today](https://github.com/mozilla/contain-facebook/pull/157#issuecomment-431138717).  This include whatsapp domains.
* I have also organized the domains so that they are in more maintainable groups.  This make _this PR's diff_ harder to read, but will make things better going forward.
Look for comments, inline, about the additions
> New domains for parent repo

- README.md
Shouldn't it be Multi-Account?
> fixed Multi-Account in README

- src/fbc-icon.svg
- src/fbc-icon2.svg
- src/manifest.json
> fix #217: updated svgs and theme_icons manifest

- .travis.yml
> Add CI caching

- src/content_script.css
- src/content_script.js
- src/fence-large.svg
- src/fence-small.svg
- src/manifest.json
Fixing part of #258. 
This pull-request adds an overlay to all Facebook-specific on-page assets. It targets them in a few ways: 
+ Any element that has the a class of `FacebookConnectButton`
+ Any `href` attribute that contains `facebook`
+ Any `data-oauthserver` attribute that contains `facebook`
+ Any element with a `title` of `share on facebook`
+ Any element with an `aria-label` of `Facebook`
+ The current method of `HREF` containing `facebook` is too broad. If you search for Facebook on Google, you can see how this doesn't match correctly. 
+ This doesn't address standard implementations of FB login. This will be addressed in a seperate pull-request.  
Recreation Steps: 
+ [Run this version](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_we …
> Facebook Non-standard Login/Like/Share Overlay 

- src/_locales/en/messages.json
- src/background.js
- src/content_script.css
- src/content_script.js
- src/manifest.json
Revised badge overlay to be psuedo/class based to injected HTML element.
> Refactored badge overlay

- src/content_script.js
> Added identifier to badge the LinkedIn registration page. 

- src/content_script.js
Completing TODO items from previous code review of PR #280. 
This PR will fix the following issues: 
+ #296
+ #301
> Content Script Code Review Revisions

- src/content_script.js
Closed #296 
- Added Medium targeted support. (Doesn't work as it doesn't block any known trackers on the page)
> Restricted positionFacebookBadge function argument to accept only one data type

- src/content_script.js
> Content_script fires on page load, and watches for DOM changes 

- src/content_script.css
- src/content_script.js
Script calculates badge position to see if there's enough room to open prompt in center, or align top/bottom to fit the screen. See screenshot examples below.
+ URL: https://secure.hi5.com/ 
+ Issue: #353 
Top (and Right):
Bottom:
> Added position detection support for top/bottom prompt alignment

- src/panel.js
Modified panel.js to open in new tab in same window, using `browser.tabs.create` function.
> 326 learn more link doesnt work

- src/content_script.js
Testing Steps: 
1. Go to https://www.premierleague.com
1. Click login
1. Login page should have badge over "Login with Facebook" button 
---
Other sites also supported: 
+ https://tinder.com
+ https://fantasymovieleague.com (Click "Log in")
> Fixed #340, Added premierleague.com support

- src/content_script.js
Test the following sites: 
- https://www.airbnb.com/
- https://www.airbnb.ca/
- https://www.pinterest.com/
- https://www.quora.com/Why-do-people-praise-Dark-Souls-so-much-I-got-it-for-Switch-and-after-getting-past-the-first-boss-I-was-confused-where-to-go-and-what-to-do-The-game-didnt-even-explain-what-half-the-items-in-my-inventory-do
- https://www.imdb.com/title/tt4154796 (Click "Share")
> Fixed #312, Added z-index detection/setting

- package.json
- src/manifest.json
> Fixed #379, Updated version number

- src/background.js
> Fixed #411, Added bubble notificaiton

- src/content_script.js
Test on the following URLs:
+ https://soundcloud.com/signin (Badge should appear over login) 
+ https://www.emag.ro/user/login
+ https://www.joinhoney.com/ (Click login for modal) 
+ https://signin.ebay.com/
+ https://etsy.com (Click login for modal)
> Add additional FB element detection support

- src/_locales/ta/messages.json
- src/_locales/tr/messages.json
Adding back to `master` from force push issue.
> Force Push Localization Sweep

- package-lock.json
- package.json
- src/manifest.json
> Bumped version number to 2.0.2

- src/img/fbc-icon-dark.svg
- src/img/fbc-icon.svg
- src/img/fbc-icon2.svg
- src/manifest.json
Fixed #503 
Icons should appear the same in the panel. Check both light and dark theme.
> Revised icon ratios, updated name of file to reflect usecase

- package.json
- src/content_script.js
- src/manifest.json
Verify badge support on the following sites: 
- https://www.freelancer.com/login
- https://www.freelancer.com/signup
- https://www.komoot.com/
- https://www.komoot.com/login
- https://web.groupme.com/signin
- https://www.doordash.com/consumer/login/
- https://www.doordash.com/consumer/signup/
> Add site support

- src/content_script.js
https://www.patreon.com/login
https://www.mixcloud.com
> Added Patreon and Mixcloud selectors

- test/features/add-domain-to-fbc.test.js
- test/features/block-subresources.test.js
background.js coverage increased from 76% to 92%
> Add feature tests for block subresources and add-domains

- src/background.js
- src/manifest.json
- test/features/already-open-reopen.test.js
- test/features/contain.test.js
This pull request sets strict_min_version to 67 as recommended by @stoically in #522 .
Additionally, it removes the previous incognito mode logic and tests, as this is handled by disabling incognito mode in manifest.json.
> Fix incognito mode behavior

- README.md
This relates to 
Issue #487 add development setup instructions to the readme
and
PR #526 Added contributing docs
> add README Development, Testing, and Links

- src/_locales/en/messages.json
Opening this PR prior to working on the feature, to get the finalized strings localized in tandem with building at the feature. (Doing that this week!) 
Thanks!
> Fixed #561 - Added new text strings for Add/Remove sites to FBC

- CONTRIBUTING.md
- README.md
- Fix broken `License` Link
- Simplify `README.md` link
> fix and simplify links

- package.json
- src/manifest.json
Cutting new release of language only updates for better localization support.
> Increased version number (patch)

- docs/container-management.md
Preview page: https://github.com/mozilla/contain-facebook/blob/wiki-container-management/docs/container-management.md
> Add wiki page for container management

- src/background.js
> Added wit.ai to the default sites list

- src/background.js
This PR adds: 
- facebookbrand.com
- novi.com
STR: 
**facebookbrand.com**
- 1. Go to https://facebookbrand.com/
- 2. **Expected:** The website should open inside the FBC
**novi.com**
- 1. Go to https://www.novi.com/ 
- 2. **Expected: ** The website should open inside the FBC
> Add additional FB domains

- package-lock.json
- package.json
- src/manifest.json
> Cut 2.3.0 release

- package-lock.json
- package.json
- src/manifest.json
No code changes. This change is required to submit to AMO for public release. (No duplicate self-hosted/AMO-hosted add-on version numbers)
> Update version to 2.3.9 for new AMO submission

- src/background.js
Threads is a new service by Meta
> Added threads.net

- package-lock.json
- package.json
- src/background.js
- src/manifest.json
- src/panel.js
- test/features/add-domain-to-fbc.test.js
- Add Threads.net URL
- Update release number
- Fix test issues
> 2.3.11 Hotfix Release Candidate 

- src/background.js
> add threads.com
